name: Coverage-Test

on:
  workflow_call:
    secrets:
        codecov_token:
          description: 'Codecov token'
          required: true

jobs:
  Coverage-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.10.0

      - name: Restore node modules cache
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  
      - name: Run tests and generate coverage
        run: npx hardhat coverage
  
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.4.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
